# NumPy

## 載入numpy套件
+ 在使用NumPy創建數組之前，必須先導入NumPy庫。
+ 如果你的環境還沒有安裝NumPy，請先安裝NumPy套件

In [21]:
# 如果沒有安裝numpy 則執行下列指令安裝(移除註解後執行，只需執行一次)
# !pip install numpy

In [2]:
import numpy as np # 導入numpy套件，並命名為np

## NumPy陣列基礎

### NumPy的資料型態：ndarray

- `shape`：陣列的形狀，表示每個維度的大小。
- `dtype`：陣列中元素的資料型別。
- `ndim`：陣列的維度數量。
- `size`：陣列中元素的總數量。

In [1]:
import numpy as np

# 創建一個一維陣列
arr = np.array([1, 2, 3, 4, 5])

print("Shape:", arr.shape)  # 輸出：(5,)
print("Data type:", arr.dtype)  # 輸出：int64
print("Number of dimensions:", arr.ndim)  # 輸出：1
print("Size:", arr.size)  # 輸出：5

Shape: (5,)
Data type: int32
Number of dimensions: 1
Size: 5


### 建立NumPy陣列
+ `np.array()`： 從現有數據（如列表或元組）建立陣列。
+ `np.zeros()`： 建立指定大小的陣列，陣列元素以0填充。
+ `np.ones()`： 建立指定大小的陣列，陣列元素以1填充。
+ `np.full()`： 建立指定大小的陣列，陣列元素以指定數值填充。
+ `np.arange()`： 建立等差陣列，指定起始值、終止值和間隔值。
+ `np.linspace()`： 建立等差陣列，指定起始值、終止值和元素個數。
+ `np.logspace()`： 建立等比陣列，指定起始值、終止值和元素個數。

> `np.arange()`和`np.linspace()`不同的是：
> + `np.arange()`則是指定數組元素的間隔
> + `np.linspace()`可以指定數組元素的個數

In [10]:
# 從列表建立陣列
arr_from_list = np.array([1, 2, 3, 4, 5])
print("Array from list:\n", arr_from_list)

# 建立全0陣列
arr_zeros = np.zeros(5)
print("Array of zeros:\n", arr_zeros)

# 建立全1陣列
arr_ones = np.ones(5)
print("Array of ones:\n", arr_ones)

# 建立全部元素指定為5的2x3陣列
arr_full = np.full((2, 3), 5)
print("Array of full:\n", arr_full)

# 建立等差數列陣列
arr_arange = np.arange(0, 10, 2) # 以 2 為間隔從 0 到 10 取值
print("Array with arange:\n", arr_arange)

# 建立等分數列陣列
arr_linspace = np.linspace(0, 1, 5) # 從 0 到 1 取 5 個數字
print("Array with linspace:\n", arr_linspace)

# 建立等比數列陣列
arr_logspace = np.logspace(1, 4, 4) # 從 10^1 到 10^4 取 4 個數字
print("Array with logspace:\n", arr_logspace)

Array from list:
 [1 2 3 4 5]
Array of zeros:
 [0. 0. 0. 0. 0.]
Array of ones:
 [1. 1. 1. 1. 1.]
Array of full:
 [[5 5 5]
 [5 5 5]]
Array with arange:
 [0 2 4 6 8]
Array with linspace:
 [0.   0.25 0.5  0.75 1.  ]
Array with logspace:
 [   10.   100.  1000. 10000.]


### NumPy數組的形狀和維度

In [6]:
# 二維數組
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("2D array:\n", arr_2d)

# 三維數組
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3D array:\n", arr_3d)


2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
3D array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [7]:
print("Shape of 2D array:", arr_2d.shape)  # 輸出：(3, 3)
print("Shape of 3D array:", arr_3d.shape)  # 輸出：(2, 2, 2)

print("Number of dimensions of 2D array:", arr_2d.ndim)  # 輸出：2
print("Number of dimensions of 3D array:", arr_3d.ndim)  # 輸出：3


Shape of 2D array: (3, 3)
Shape of 3D array: (2, 2, 2)
Number of dimensions of 2D array: 2
Number of dimensions of 3D array: 3


### 索引和切片選取數據

In [8]:
# 一維數組的索引和切片
arr = np.array([1, 2, 3, 4, 5])
print("Element at index 2:", arr[2])  # 輸出：3
print("Slice from index 1 to 3:", arr[1:4])  # 輸出：[2 3 4]

# 二維數組的索引和切片
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Element at (1, 2):", arr_2d[1, 2])  # 輸出：6
print("Slice of first row:", arr_2d[0, :])  # 輸出：[1 2 3]
print("Slice of first column:", arr_2d[:, 0])  # 輸出：[1 4 7]


Element at index 2: 3
Slice from index 1 to 3: [2 3 4]
Element at (1, 2): 6
Slice of first row: [1 2 3]
Slice of first column: [1 4 7]


## NumPy基本運算

### 四則運算
對於NumPy數組的四則運算（加、減、乘、除），這些運算都是對數組中的每個元素進行的。

In [12]:
import numpy as np

# 創建兩個數組
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# 加法
print("arr1 + arr2:", arr1 + arr2)

# 減法
print("arr1 - arr2:", arr1 - arr2)

# 乘法
print("arr1 * arr2:", arr1 * arr2)

# 除法
print("arr1 / arr2:", arr1 / arr2)


arr1 + arr2: [5 7 9]
arr1 - arr2: [-3 -3 -3]
arr1 * arr2: [ 4 10 18]
arr1 / arr2: [0.25 0.4  0.5 ]


### 統計運算

In [11]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# 求和
print("Sum:", np.sum(arr))

# 平均值
print("Mean:", np.mean(arr))

# 標準差
print("Standard deviation:", np.std(arr))

# 最大值和最小值
print("Max:", np.max(arr))
print("Min:", np.min(arr))


Sum: 15
Mean: 3.0
Standard deviation: 1.4142135623730951
Max: 5
Min: 1


### 數學函數運算

In [13]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# 指數函數
print("Exponential:", np.exp(arr))

# 對數函數
print("Natural logarithm:", np.log(arr))
print("Base-10 logarithm:", np.log10(arr))

# 三角函數
print("Sine:", np.sin(arr))
print("Cosine:", np.cos(arr))


Exponential: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Natural logarithm: [0.         0.69314718 1.09861229 1.38629436 1.60943791]
Base-10 logarithm: [0.         0.30103    0.47712125 0.60205999 0.69897   ]
Sine: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
Cosine: [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]


### 數組的排序與搜尋


In [14]:
import numpy as np

arr = np.array([5, 3, 1, 4, 2])

# 排序
sorted_arr = np.sort(arr)
print("Sorted array:", sorted_arr)

# 搜索最大值和最小值的索引
max_index = np.argmax(arr)
min_index = np.argmin(arr)
print("Index of max value:", max_index)
print("Index of min value:", min_index)


Sorted array: [1 2 3 4 5]
Index of max value: 0
Index of min value: 2


## 線性代數運算

### 矩陣乘法

In [15]:
import numpy as np

# 創建兩個二維數組（矩陣）
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# 使用np.dot()進行矩陣乘法
result_dot = np.dot(A, B)
print("Result using np.dot():\n", result_dot)

# 使用np.matmul()進行矩陣乘法
result_matmul = np.matmul(A, B)
print("Result using np.matmul():\n", result_matmul)

Result using np.dot():
 [[19 22]
 [43 50]]
Result using np.matmul():
 [[19 22]
 [43 50]]


### 求矩陣的逆矩陣

### 求解線性方程組

In [15]:
import numpy as np

# 創建係數矩陣A和常數向量b
A = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])

# 使用np.linalg.solve()求解方程組
x = np.linalg.solve(A, b)
print("Solution:", x)  # 輸出：[2. 3.]


Solution: [2. 3.]


## NumPy的廣播機制

In [16]:
import numpy as np

# 創建兩個不同形狀的陣列
arr1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2 = np.array([1, 0, 1])

# 查看兩個陣列的形狀
print("Shape of arr1:", arr1.shape)
print("Shape of arr2:", arr2.shape)

# 使用廣播機制進行加法運算
result = arr1 + arr2
print("Result of broadcasting addition:\n", result)


Shape of arr1: (3, 3)
Shape of arr2: (3,)
Result of broadcasting addition:
 [[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]]


## NumPy向量化運算

In [17]:
import numpy as np

# 建立一個形狀為(3, 3)的數組
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# 使用內置向量化函數對數組進行運算
sin_arr = np.sin(arr)
print("Sine of array:\n", sin_arr)

cos_arr = np.cos(arr)
print("Cosine of array:\n", cos_arr)

exp_arr = np.exp(arr)
print("Exponential of array:\n", exp_arr)


Sine of array:
 [[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825  0.41211849]]
Cosine of array:
 [[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]
 [ 0.75390225 -0.14550003 -0.91113026]]
Exponential of array:
 [[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]


In [19]:
import numpy as np

# 自定義函數
def square(x):
    return x ** 2

# 創建一個形狀為(3, 3)的數組
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# 將自定義函數向量化
vectorized_square = np.vectorize(square)

# 應用向量化函數到數組
squared_arr = vectorized_square(arr)
print("Squared array:\n", squared_arr)


Squared array:
 [[ 1  4  9]
 [16 25 36]
 [49 64 81]]
